# Generated by Django 3.1.2 on 2020-10-20 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_medical',
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_patient',
        ),
        migrations.AddField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('medical', 'Doctor'), ('patient', 'Paciente')], default='Paciente', max_length=9),
        ),
        migrations.AlterField(
            model_name='patient',
            name='patient_status',
            field=models.CharField(choices=[('N', 'Neutro'), ('+', 'Positivo'), ('-', 'Negativo'), ('F', 'Fallecido')], default='Positivo', max_length=1),
        ),
    ]
